In [1]:
# Loading Dataset

import pandas as pd
df = pd.read_csv("C:/Users/Administrator/Desktop/Python/DataSets/DIsssSdata.csv")

# df.head(5)
# print(df.head(2))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   OrderID            2000 non-null   object
 1   Order_Date         2000 non-null   object
 2   Expiry_Date        2000 non-null   object
 3   Pallet_Size        2000 non-null   int64 
 4   Route_Type         2000 non-null   object
 5   Mode_of_Transport  2000 non-null   object
 6   Urgent_Order_Flag  2000 non-null   object
 7   Fragility          2000 non-null   object
 8   Dispatch_Window    2000 non-null   object
 9   Temp_Sensitive     2000 non-null   object
dtypes: int64(1), object(9)
memory usage: 156.4+ KB


In [2]:
# Convert string columns to datetime
df['Expiry_Date'] = pd.to_datetime(df['Expiry_Date'], format='%d/%m/%Y')
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='%d/%m/%Y')

# Calculate expiry range
df['Expiry_Days_Left'] = (df['Expiry_Date'] - df['Order_Date']).dt.days

# Display
print(df[['OrderID', 'Order_Date', 'Expiry_Date', 'Expiry_Days_Left']].head(5))


                   OrderID Order_Date Expiry_Date  Expiry_Days_Left
0  D0689266-88BE-4949-B7A4 2025-06-15  2026-02-08               238
1  85E9D4B1-BB58-4F2D-86BA 2025-06-18  2025-11-08               143
2  DA6CC913-1DC3-4E6A-B78E 2025-06-20  2025-10-25               127
3  B6521275-0E3B-4D7E-8A14 2025-06-16  2026-12-02               534
4  8FDBC5E6-C82B-48D2-9B97 2025-06-17  2026-05-24               341


In [4]:
# Reorder columns (make Expiry_Days_Left 2nd)
cols = df.columns.tolist()
cols.insert(1, cols.pop(cols.index('Expiry_Days_Left')))
df = df[cols]

# Save back to CSV
df.to_csv("C:/Users/Administrator/Desktop/Python/DataSets/DISddddata.csv", index=False)

In [8]:
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   OrderID            2000 non-null   object
 1   Expiry_Days_Left   2000 non-null   int64 
 2   Order_Date         2000 non-null   object
 3   Expiry_Date        2000 non-null   object
 4   Pallet_Size        2000 non-null   int64 
 5   Route_Type         2000 non-null   object
 6   Mode_of_Transport  2000 non-null   object
 7   Urgent_Order_Flag  2000 non-null   object
 8   Fragility          2000 non-null   object
 9   Dispatch_Window    2000 non-null   object
 10  Temp_Sensitive     2000 non-null   object
dtypes: int64(2), object(9)
memory usage: 172.0+ KB


In [9]:
#Loading Required Liaberies ( WORKING WITH RANDOM FOREST KNN HANDELED BY SCIKIT LEARN )

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
import joblib  # For saving model


In [12]:
#Loading DataSheet
df = pd.read_csv("C:/Users/Administrator/Desktop/Python/DataSets/DISddddata.csv")
# df.head(3)

In [13]:
# df['Expiry_Date'] = pd.to_datetime(df['Expiry_Date'], format='%Y-%m-%d')
# df['Dispatch_Window'] = pd.to_datetime(df['Dispatch_Window'], format='%Y-%m-%d')
# df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='%Y-%m-%d')

# Convert Dispatch_Window and Order_Date to delivery_window_days
df['Dispatch_Window'] = pd.to_datetime(df['Dispatch_Window'])
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Delivery_Window_Days'] = (df['Dispatch_Window'] - df['Order_Date']).dt.days


C:\Users\Administrator\AppData\Local\Temp\ipykernel_8012\771286952.py:6: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Dispatch_Window'] = pd.to_datetime(df['Dispatch_Window'])


In [52]:
import numpy as np

def assign_priority_fuzzy_sigmoid_robust(row,
                                         expiry_threshold=120,          # 2 months
                                         delivery_threshold=10,         # 10 days
                                         high_cutoff=0.6,
                                         medium_cutoff=0.4,
                                         weights=None,
                                         k=0.08):                       # Sharper sigmoid
    """
    Robust industrial fuzzy logic for assigning priority labels to dispatch items.
    Combines rule-based overrides and smooth sigmoid-based scoring.

    Parameters:
        expiry_threshold (int): Days threshold where expiry becomes critical
        delivery_threshold (int): Days threshold for delivery urgency
        high_cutoff (float): Score threshold for High priority
        medium_cutoff (float): Score threshold for Medium priority
        weights (dict): Weight mapping for all five parameters
        k (float): Sigmoid steepness factor (higher = sharper cutoff)

    Returns:
        str: 'High', 'Medium', or 'Low'
    """
    if weights is None:
        weights = {
            'expiry': 0.4,
            'delivery': 0.3,
            'urgent': 0.2,
            'temp': 0.05,
            'fragile': 0.05
        }

    expiry_days = row['Expiry_Days_Left']
    delivery_days = row['Delivery_Window_Days']

    # 🧠 Sigmoid fuzzy scores (scaled to smooth transitions)
    expiry_score = 1 / (1 + np.exp(k * (expiry_days - expiry_threshold)))
    delivery_score = 1 / (1 + np.exp(k * (delivery_days - delivery_threshold)))

    urgent_score = 1 if row['Urgent_Order_Flag'] == 'Yes' else 0
    temp_score = 1 if row['Temp_Sensitive'] == 'Yes' else 0
    fragile_score = 1 if row['Fragility'] == 'Yes' else 0

    # 🔒 Hard Rule Overrides (Business-critical triggers)
    # Rule 1: Expiry very soon AND urgent
    if expiry_days <= 30 and row['Urgent_Order_Flag'] == 'Yes':
        return 'High'

    # Rule 2: Temp-sensitive AND near expiry
    if expiry_days <= 30 and row['Temp_Sensitive'] == 'Yes':
        return 'High'

    # Rule 3: Tight delivery window AND urgent
    if delivery_days <= 5 and row['Urgent_Order_Flag'] == 'Yes':
        return 'High'

    # Rule 4: Expiry + Delivery both extremely tight
    if expiry_days <= 10 and delivery_days <= 5:
        return 'High'

    # Rule 5: Fragile and urgent (special handling needed)
    if row['Urgent_Order_Flag'] == 'Yes' and row['Fragility'] == 'Yes':
        return 'High'

    # Rule 6: Very relaxed, non-urgent case
    if expiry_days > 600 and delivery_days > 45 and row['Urgent_Order_Flag'] == 'No':
        return 'Low'

    # 🎯 Weighted fuzzy scoring
    total_score = (
        expiry_score * weights['expiry'] +
        delivery_score * weights['delivery'] +
        urgent_score * weights['urgent'] +
        temp_score * weights['temp'] +
        fragile_score * weights['fragile']
    )

    # 🔽 Priority Classification
    if total_score >= high_cutoff:
        return 'High'
    elif total_score >= medium_cutoff:
        return 'Medium'
    else:
        return 'Low'



df['Priority_Label'] = df.apply(assign_priority_fuzzy_sigmoid_robust, axis=1)

# Split data
high_df = df[df['Priority_Label'] == 'High']
medium_df = df[df['Priority_Label'] == 'Medium']
low_df = df[df['Priority_Label'] == 'Low']

print(f"High Priority Orders: {len(high_df)}")
print(f"Medium Priority Orders: {len(medium_df)}")
print(f"Low Priority Orders: {len(low_df)}")


High Priority Orders: 678
Medium Priority Orders: 202
Low Priority Orders: 1120


In [53]:
#dataset for ml

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Step 1: Feature Selection
features = [
    'Pallet_Size',
    'Route_Type',
    'Mode_of_Transport',
    'Urgent_Order_Flag',
    'Fragility',
    'Temp_Sensitive',
    'Expiry_Days_Left',
    'Dispatch_Window',  # will convert this to days
    'Order_Date'
]

# Convert Dispatch_Window and Order_Date to delivery_window_days
df['Dispatch_Window'] = pd.to_datetime(df['Dispatch_Window'])
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Delivery_Window_Days'] = (df['Dispatch_Window'] - df['Order_Date']).dt.days

# Keep only required features + label
ml_df = df[[
    'Pallet_Size', 'Route_Type', 'Mode_of_Transport', 'Urgent_Order_Flag',
    'Fragility', 'Temp_Sensitive', 'Expiry_Days_Left', 'Delivery_Window_Days', 
    'Priority_Label'
]]

# Encode categorical columns
label_encoders = {}
for col in ['Route_Type', 'Mode_of_Transport', 'Urgent_Order_Flag', 'Fragility', 'Temp_Sensitive']:
    le = LabelEncoder()
    ml_df.loc[:, col] = le.fit_transform(ml_df[col])
    label_encoders[col] = le

# Encode output label
le_priority = LabelEncoder()
# ml_df.loc[:, 'Priority_Label'] = le_priority.fit_transform(ml_df['Priority_Label'])
ml_df.loc[:, 'Priority_Label'] = le_priority.fit_transform(ml_df['Priority_Label'])
# ml_df['Priority_Label'] = le_priority.fit_transform(ml_df['Priority_Label'].astype(str))



In [54]:
#BRUT FORCE

# Manually map string labels to integers
priority_mapping = {
    'Low': 0,
    'Medium': 1,
    'High': 2
}

# Apply the mapping manually
df['Encoded_Priority_Label'] = df['Priority_Label'].map(priority_mapping)

# Check results
print(df['Encoded_Priority_Label'].unique())
print(df['Encoded_Priority_Label'].dtype)


[0 2 1]
int64


In [56]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le_priority.classes_))


Confusion Matrix:
 [[ 89   0   0]
 [  1  52   4]
 [  0   0 254]]

Classification Report:
               precision    recall  f1-score   support

        High       0.99      1.00      0.99        89
         Low       1.00      0.91      0.95        57
      Medium       0.98      1.00      0.99       254

    accuracy                           0.99       400
   macro avg       0.99      0.97      0.98       400
weighted avg       0.99      0.99      0.99       400



In [ ]:
print(df['Priority_Label'].value_counts())

print(df['Priority_Label'].isnull().sum())
 


Priority_Label
High      1269
Low        447
Medium     284
Name: count, dtype: int64
0


In [57]:
#SEPERATE DATAFRAMES FOR PRIORITY

high_df = df[df['Priority_Label'] == 'High']
medium_df = df[df['Priority_Label'] == 'Medium']
low_df = df[df['Priority_Label'] == 'Low']

 
print(f"High Priority Orders: {len(high_df)}")
print(f"Medium Priority Orders: {len(medium_df)}")
print(f"Low Priority Orders: {len(low_df)}")

High Priority Orders: 678
Medium Priority Orders: 202
Low Priority Orders: 1120


In [58]:
# Save model
joblib.dump(model, 'C:\\Users\\Administrator\\Desktop\\Python\\TrainedModel\\dispatch_priority_model.pkl')

# # Also save encoders if needed later
joblib.dump(label_encoders, 'C:\\Users\\Administrator\\Desktop\\Python\\TrainedModel\\label_encoders.pkl')
joblib.dump(le_priority, 'C:\\Users\\Administrator\\Desktop\\Python\\TrainedModel\\priority_label_encoder.pkl')

['C:\\Users\\Administrator\\Desktop\\Python\\TrainedModel\\priority_label_encoder.pkl']

In [59]:
# 3 MODEL USING AND HYPER PARAMETERS 

for col, le in label_encoders.items():
    print(f" Test Data Format ::: {col} classes: {le.classes_}")

 Test Data Format ::: Route_Type classes: ['Intercity' 'Interstate' 'Local']
 Test Data Format ::: Mode_of_Transport classes: ['Big Truck' 'Medium Truck' 'Small Truck']
 Test Data Format ::: Urgent_Order_Flag classes: ['No' 'Yes']
 Test Data Format ::: Fragility classes: ['No' 'Yes']
 Test Data Format ::: Temp_Sensitive classes: ['No' 'Yes']


In [61]:
import joblib
import pandas as pd

# Load model and encoders
model = joblib.load('C:\\Users\\Administrator\\Desktop\\Python\\TrainedModel\\dispatch_priority_model.pkl')
label_encoders = joblib.load('C:\\Users\\Administrator\\Desktop\\Python\\TrainedModel\\label_encoders.pkl')
le_priority = joblib.load('C:\\Users\\Administrator\\Desktop\\Python\\TrainedModel\\priority_label_encoder.pkl')

# Test data with possible new/unseen values
new_data = pd.DataFrame([
    {
        'Pallet_Size': 100,
        'Route_Type': 'Intercity',        # OK
        'Mode_of_Transport': 'Medium Truck',  # OK
        'Urgent_Order_Flag': 'Yes',
        'Fragility': 'Yes',
        'Temp_Sensitive': 'Yes',
        'Expiry_Days_Left': 5,
        'Delivery_Window_Days': 10
    },
    {
        'Pallet_Size': 80,
        'Route_Type': 'Intracity',
        'Mode_of_Transport': 'Mini Truck',
        'Urgent_Order_Flag': 'No',
        'Fragility': 'Yes',
        'Temp_Sensitive': 'No',
        'Expiry_Days_Left': 90,
        'Delivery_Window_Days': 25
    },
    {
        'Pallet_Size': 120,
        'Route_Type': 'Interstate',
        'Mode_of_Transport': 'Big Truck',
        'Urgent_Order_Flag': 'No',
        'Fragility': 'No',
        'Temp_Sensitive': 'No',
        'Expiry_Days_Left': 360,
        'Delivery_Window_Days': 60
    }
])

# Encode new data safely by replacing unseen labels
for col in ['Route_Type', 'Mode_of_Transport', 'Urgent_Order_Flag', 'Fragility', 'Temp_Sensitive']:
    le = label_encoders[col]
    
    # Ensure all values are known to encoder
    new_data[col] = new_data[col].apply(lambda x: x if x in le.classes_ else le.classes_[0])
    
    # Re-transform with safe values
    new_data[col] = le.transform(new_data[col])

# Predict
prediction_encoded = model.predict(new_data)
prediction_label = le_priority.inverse_transform(prediction_encoded)

# Results
new_data['Predicted_Priority'] = prediction_label
print(new_data[['Pallet_Size', 'Expiry_Days_Left', 'Delivery_Window_Days', 'Predicted_Priority']])


   Pallet_Size  Expiry_Days_Left  Delivery_Window_Days Predicted_Priority
0          100                 5                    10             Medium
1           80                90                    25             Medium
2          120               360                    60                Low


In [62]:
# Assuming 'df' contains the final dataframe after priority assignment
csv_path = "C:/Users/Administrator/Desktop/Python/DataSets/FINALDIS.csv"
df.to_csv(csv_path, index=False)